import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CartButton from "./ui/CartButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen flex flex-col bg-white text-black">
          <header className="sticky top-0 z-40 backdrop-blur bg-white/70 border-b border-black/10">
            <div className="mx-auto max-w-6xl h-16 flex items-center justify-between px-4">
              <Link href="/" className="text-xl font-semibold tracking-tight">TerMo</Link>
              <nav className="hidden md:flex gap-6 text-sm items-center">
                <Link href="/">Home</Link>
                <Link href="/products">Products</Link>
                <Link href="/support/faq">Support</Link>
                <CartButton />
              </nav>
            </div>
          </header>
          <main className="flex-1">{children}</main>
          <footer className="border-t border-black/10 py-10">
            <div className="mx-auto max-w-6xl text-sm flex flex-col md:flex-row items-center justify-between gap-4 px-4">
              <p className="opacity-70">© {new Date().getFullYear()} TerMo. All rights reserved.</p>
              <div className="flex gap-6 opacity-80">
                <Link href="/support/docs">Docs</Link>
                <Link href="/support/contact">Contact</Link>
                <Link href="/support/locations">Locations</Link>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
